### ISSUE TITLE
Zooming, panning, rotating

### ISSUE THREAD

**Issue by brenthuisman** [thorstenhater/arbor-gui#1]
Right now rotating requires a pointer input with horizontal scrolling, i.e. a mousepad. For those without laptops, a UI control for this would be nice (and/or CTRL+vert scroll or sth). Panning is not possible, would also be nice (click+drag).

**Comment by thorstenhater** [comment]
Hi,

it's on my list, along with some more interesting things like locking the view to a locset / region. That said, it's currently a low priority thing, as more functional things are higher up.

T

**Comment by thorstenhater** [comment]
You can now
- Zoom: Scroll up/down
- Pan: Alt+Left Mouse Drag
- Rotate: Left Mouse Drag

**Comment by brenthuisman** [comment]
Alt+LMB is already bound on Linux (move window). You should improve your override or choose another key (RMB drag?).
