### ISSUE TITLE
Scrolling/panning: seems to be going diagonally

### ISSUE THREAD

**Issue by brenthuisman** [thorstenhater/arbor-gui#12]
Might be related to the platform (Linux): when I hold down CTRL and drag to pan, the viewport moves diagonally when the cursor is dragged at right angles, i.e. not in the direction of the cursor. Because this vector always seems to arc rightward, the cell tends to disappear on the LHS of the viewport.

Is it possible that the cell is anchored at the cursor position and dragged in the direction of the cursor, rather than/in addition to scroll? I suppose that was already the intent at [1], but there I can't see what might explain what I see.

[1] https://github.com/thorstenhater/arbor-gui/blob/master/src/window.cpp#L35

**Comment by thorstenhater** [comment]
No, the panning _is_ definitely broken. It has been on my internal list for a few days.
