### ISSUE TITLE
Please put the regions in a label_dict

### ISSUE THREAD

**Issue by brenthuisman** [thorstenhater/arbor-gui#2]
It will help fix https://github.com/arbor-sim/arbor/issues/1229

**Comment by thorstenhater** [comment]
I have explored that direction in the past, but it's not good solution for the problem, as one neither edit the names, ie keys, nor delete entries. Also, only valid name/{locset,region} combination can be entered.

**Comment by brenthuisman** [comment]
Do you need to use an arb::label_dict, or could you use your own in the GUI? Which you could edit as you please? Only when eventually it is possible to run a simulation would you need to setup an actual arb::label_dict.

**Comment by thorstenhater** [comment]
if the error is what you say -- namely that this expression needs a label_dict to parse -- then I cannot roll my own, as it would duplicate arb::label_dict.

**Comment by brenthuisman** [comment]
I was putting it in the wrong place (locsets). Whoopsy!
