### ISSUE TITLE
Overlapping regions

### ISSUE THREAD

**Issue by brenthuisman** [thorstenhater/arbor-gui#3]
Region that overlap are not necessarily painted in the way one would expect. A soluation involves formalizing what we expect, and then the technical challenge of painting to any one (part of a) region just once. Or alpha.

**Comment by thorstenhater** [comment]
It turns out that my preferred solution -- having alpha transparency -- is not as easy as one might imagine. Expect this to take a long while.

**Comment by thorstenhater** [comment]
To elaborate on the last point:

To have transparency work correctly all polygons need to be sorted front -- back. That's quite expensive and only recommended for few instances, which surely is exceeded here.

However, the latests version includes an info window listing the region under the mouse cursor. I think this resolves the,
but feel free to disagree and re-open.
