### ISSUE TITLE
Deleting all regions from imported NeuroML file leads to strange behaviour and segfault

### ISSUE THREAD

**Issue by llandsmeer** [thorstenhater/arbor-gui#32]
To reproduce
 1. Install arbor-gui
 2. Download a NeuroML file (I used [this one](https://github.com/llandsmeer/io/blob/main/SmolModelPorts/model/Cells/C51A_scaled_exp_resample_5.cell.nml), or similarly [this one](https://github.com/FerreroRoche/Multicompartmental-NeuroML/blob/master/Cells/C51A_scaled_exp_resample_5.cell.nml))
 3. File > Morphology > Load
 4. Under Location > Regions, start deleting all regions that are not soma_group, dendrite_group or axon_group

Behaviour: At first, soma_group will change in random garbled text (might change continuously). After a while a segfault will occur

**Comment by llandsmeer** [comment]
Just did a debug build with the latest `master`. Apparently another possible behavior is a segfault after deleting everything and closing the application.

Second time (in gdb), segfault happened inside `_int_malloc()` due to a `new String` operation originating from `src/location.hpp:30` (copy operator) during a `gui_state::update()` (if that helps)

**Comment by llandsmeer** [comment]
The string in question is this:

```
#9  0x000055555560bbaf in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (this=0x555556ee78d8,
    __str="\220\260\224VUU\000\000\020\341\235\367\377\177\000\000\220\260\224VUU\000\000\220\260\224VUU\000\000oin (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (j"...)
```

**Comment by thorstenhater** [comment]
Hi,

this should be fixed now. Thanks for reporting.

T

**Comment by llandsmeer** [comment]
I just checked out the latest `main` branch and the error is gone, thanks!
