### ISSUE TITLE
Compile in version/commit information

### ISSUE THREAD

**Issue by schmitts** [thorstenhater/arbor-gui#37]
To ease debugging in case of problems it would be helpful if the version, e.g., the commit hash plus dirty flag, could be retrieved from within the GUI. E.g. in the main window title or some "about" box. Command line usage via `arbor-gui --version` would also be good to have.

**Comment by thorstenhater** [comment]
<img width="1392" alt="Screenshot 2021-04-27 at 10 21 52" src="https://user-images.githubusercontent.com/24411438/116209716-78b8f700-a742-11eb-8465-21c7d6b5ae99.png">

Done
