### ISSUE TITLE
Allow to change drawing order of regions

### ISSUE THREAD

**Issue by schmitts** [thorstenhater/arbor-gui#39]
When defining regions to be colored, it would be good if the order in which the coloring is done can be chosen. Like e.g. layers in a graphics program. Some level of transparency would also be helpful to define/debug definitions of overlapping regions.

**Comment by thorstenhater** [comment]
- I am not quite sure what is meant by 'order of colouring', do you mean the draw order, akin to z-order in matplotlib?
   If so, I can imagine to make an attempt at drag'n'drop in the region/locset list. I was tempted to do that before, but it was never important enough.
- Transparency has been discussed before and is -- sadly -- astonishingly hard to get right and performant. (All triangles need to be sorted by depth from the camera. It is usually not advisable to have more than 'a few' transparent triangles.)

**Comment by schmitts** [comment]
Yes, like the z-order.

**Comment by thorstenhater** [comment]
Ok, that can be done, I think. If you like, we are open to PRs ;)

**Comment by thorstenhater** [comment]
Added this
- Regions/Locset can be re-ordered by Drag and Drop
- Regions 'stack' in the given order, ie they will hide anything below them in the list if defined in the same location.
