### ISSUE TITLE
Locset (terminal) drawing issue

### ISSUE THREAD

**Issue by brenthuisman** [thorstenhater/arbor-gui#4]
Adding a locset with expression `(terminal)` draws triangles are every distal point of every segment.

![Screenshot_20201208_121524](https://user-images.githubusercontent.com/2943652/101477191-2fad0580-394f-11eb-9af6-9c73f3e095eb.png)

**Comment by thorstenhater** [comment]
Yes, `(terminal)` generates a marker at every distal point. That's the intended behaviour. If you do not like the rendered markers, you can turn them off using the eye-icon.

**Comment by brenthuisman** [comment]
`(terminal)` is here defined as the distal points of segments without children, i.e. ends of the tree.
https://arbor.readthedocs.io/en/latest/concepts/morphology.html#morph-segment-definitions

**Comment by thorstenhater** [comment]
OK, this was not immediately clear from the question.
This then turns into a question about arbor's morphologies.

**Comment by brenthuisman** [comment]
I havn't saved any evidence, but I certainly recall drawing `(terminal)` and getting just the ends of the tree.

**Comment by thorstenhater** [comment]
The arbor docs agree with that sentiment. Could you provide a current example?

**Comment by brenthuisman** [comment]
Example of what?

Trying to build the architecture branch generates build errors.

**Comment by thorstenhater** [comment]
Of the behaviour in arbor.

**Comment by brenthuisman** [comment]
The current behavior is in the screenshot.

**Comment by brenthuisman** [comment]
Using the Python lib built from arbor-gui's arbor, this swc:

```
import arbor
morph = arbor.load_swc_allen("cell.swc")
labels = arbor.label_dict()
cell = arbor.cable_cell(morph, labels)
print(cell.locations('(terminal)'))
```

generates

`[(location 3 1), (location 4 1), (location 5 1), (location 7 1), (location 9 1), (location 10 1), (location 11 1), (location 13 1), (location 14 1), (location 16 1), (location 18 1), (location 20 1), (location 21 1), (location 23 1), (location 25 1), (location 27 1), (location 28 1), (location 34 1), (location 35 1), (location 36 1), (location 37 1), (location 39 1), (location 42 1), (location 43 1), (location 45 1), (location 49 1), (location 50 1), (location 52 1), (location 54 1), (location 60 1), (location 61 1), (location 63 1), (location 65 1), (location 67 1), (location 69 1), (location 70 1), (location 73 1), (location 75 1), (location 77 1), (location 78 1), (location 82 1), (location 84 1), (location 85 1), (location 87 1), (location 88 1), (location 89 1), (location 90 1), (location 91 1), (location 93 1), (location 94 1), (location 95 1), (location 96 1), (location 98 1), (location 100 1), (location 101 1), (location 102 1)]`

**Comment by thorstenhater** [comment]
Fixed; there was an error in the conversion from morphology to segment tree.
