### ISSUE TITLE
Feature request: export/save-to-file

### ISSUE THREAD

**Issue by schmitts** [thorstenhater/arbor-gui#45]
It would be handy to have an export/save-to-file feature available to avoid having to use screenshots. If possible, the resolution of the saved image could be different from the on screen render.

**Comment by thorstenhater** [comment]
This functionality is currently (sans resolution) implemented. R-Click cell image > Export Snapshot.

**Comment by thorstenhater** [comment]
<img width="1392" alt="Screenshot 2021-05-20 at 09 53 37" src="https://user-images.githubusercontent.com/24411438/118940733-4a999200-b951-11eb-8a88-0f9df00eb75f.png">
