### ISSUE TITLE
Opening `Probes` section crashes GUI

### ISSUE THREAD

**Issue by Helveg** [thorstenhater/arbor-gui#49]
When I open the `Probes` section the following error occurs:

```
terminate called after throwing an instance of 'arb::no_such_mechanism'
  what():  no mechanism BBP in catalogue
Aborted
```

**Comment by Helveg** [comment]
Hmm, there's not much more to it. I built arbor-gui, opened it, tried clicking on some things and this happened. It still happens so I can debug however you tell me to :)

**Comment by thorstenhater** [comment]
A backtrace from a debug build would be helpful. From the look of things there is an error in the lookup of mechanisms; the mechanism name and catalogue are confused.

**Comment by Helveg** [comment]
How to make a debug build?

**Comment by thorstenhater** [comment]
`cmake .. -DCMAKE_BUILD_TYPE=debug <rest as before>`

**Comment by thorstenhater** [comment]
This should be OK by now, if not, please re-open.
