### ISSUE TITLE
Stochastic ASC parsing error

### ISSUE THREAD

**Issue by Helveg** [thorstenhater/arbor-gui#52]
Sporadically the attached ASC file throws the following error, but usually it loads fine:

```
[2021-05-18 18:12:04.928] [debug] Reading ACC from /home/robin/stellate.asc
terminate called after throwing an instance of 'arborio::cableio_parse_error'
  what():  Unexpected term Unexpected '(' at the end of input. at :5:1
Aborted
```
[stellate.zip](https://github.com/thorstenhater/arbor-gui/files/6502787/stellate.zip)

**Comment by thorstenhater** [comment]
Could you provide the example file?

**Comment by thorstenhater** [comment]
Yes. Could it be that you tried to open a NeuroLucida (.asc) morphology file using the Arbor Cable Cell format reader (.acc)?
That said, these exception should not cause a crash.
