### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by brenthuisman** [thorstenhater/arbor-gui#70]
Opening `morph.nml` from Arbor's `python/examples` dir gives a segfault. Arbor-Gui configures Arbor with NML support, so, there is a possible problem. This is not with the AppImage btw, a good old CMake build installed to `~/.local`, so no potential library problems. Output is not very helpful (straight to segfault). Have `nml` files been tested?

**Comment by thorstenhater** [comment]
That's sad to hear, not only we configure arbor w/ NML support, but we also have loaders for NML morphology. 
Just to make sure, you did try to open a morphology, not a cable cell?
NML support has indeed been tested with some examples (found in the `data` dir), but not the one you quote.
A stacktrace would be helpful (compile in debug mode, run under gdb/lldb).
